spring:
  rabbitmq:
    host: mq1.taurus.pub
    port: 5672
    username: devpush
    password: xwC32LLDRJ1wj4x2wUdQkQ57MQuf9szI
    listener:
      simple:
        acknowledge-mode: manual
    virtual-host: /devpushost
